name: narrative_clean
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - scikit-learn
  - pyarrow
  - matplotlib
  - pillow
  - spacy
  - spacy-model-en_core_web_sm    # <-- add this (conda-forge provides it)
  - nltk
  - joblib
  - ipykernel
  - jinja2
  - tqdm
  - pip-tools
  - wordcloud
  - plotly
  - kaleido
  - sentence-transformers
  - transformers
  - sentencepiece
  - huggingface-hub
  - pytorch                       
  - pip:
      - streamlit==1.49.1
      - streamlit-option-menu==0.4.0
      - streamlit_chat
      - tokenizers
      - torchvision               
      - python-docx
      - pdfplumber
