blank_issues_enabled: false
contact_links:
  - name: Questions / Discussions
    url: https://github.com/dipeshkumar123/ai-narrative-nexus/discussions
    about: Ask questions, share ideas, or discuss enhancements here.
