# src/reporting.py
"""
Simple HTML report generator that collects visuals + summaries into one HTML file.

Usage from command line (example):
python -c "from src.reporting import generate_report; generate_report('job_desc', 'viz/job_desc', 'models/job_desc/nmf/top_words.json', 'summaries/job_desc/summaries_extractive.json')"

Function signature:
generate_report(report_name, viz_dir, top_words_path, summaries_path, out_dir='reports')

It returns path to the generated HTML.
"""
import json
from pathlib import Path
from datetime import datetime
from typing import Optional

HTML_TEMPLATE = """
<!doctype html>
<html>
<head>
  <meta charset="utf-8"/>
  <title>Text Analysis Report - {title}</title>
  <style>
    body {{ font-family: Arial, Helvetica, sans-serif; margin: 24px; }}
    h1,h2,h3 {{ color: #222; }}
    .grid {{ display:grid; grid-template-columns: repeat(auto-fit,minmax(320px,1fr)); gap: 18px; }}
    .card {{ border:1px solid #ddd; padding:12px; border-radius:6px; background:#fff; box-shadow: 0 1px 2px rgba(0,0,0,0.04); }}
    img {{ max-width:100%; height:auto; display:block; margin: 8px 0; }}
    pre {{ white-space: pre-wrap; word-wrap: break-word; background:#f7f7f7; padding:8px; border-radius:4px; }}
  </style>
</head>
<body>
  <h1>Text Analysis Report — {title}</h1>
  <p>Generated: {ts}</p>

  <h2>Overview</h2>
  <div class="card">
    <p><strong>Visuals directory:</strong> {viz_dir}</p>
    <p><strong>Top words JSON:</strong> {top_words_path}</p>
    <p><strong>Summaries:</strong> {summaries_path}</p>
  </div>

  <h2>Topic Sizes</h2>
  <div class="card"><img src="{topic_sizes_img}" alt="Topic sizes"></div>

  <h2>Wordclouds</h2>
  <div class="grid">
    {wordcloud_imgs}
  </div>

  <h2>Sentiment per Topic</h2>
  <div class="grid">
    {sentiment_imgs}
  </div>

  <h2>Summaries (per topic)</h2>
  <div class="grid">
    {summary_cards}
  </div>

  <footer style="margin-top:40px; font-size:0.9em; color:#666;">
    <p>Report generated by text-analysis-project</p>
  </footer>
</body>
</html>
"""

def generate_report(report_name: str,
                    viz_dir: str,
                    top_words_path: Optional[str],
                    summaries_path: Optional[str],
                    out_dir: str = "reports") -> str:
    """
    Build an HTML report from provided assets.

    - report_name: short label (e.g., 'job_desc')
    - viz_dir: folder where topic_sizes.png, wordcloud_topic_*.png, sentiment_topic_*.png live
    - top_words_path: optional JSON path (for reference)
    - summaries_path: optional JSON path with summaries per topic
    - out_dir: folder to save HTML report
    """
    viz = Path(viz_dir)
    out_root = Path(out_dir)
    out_root.mkdir(parents=True, exist_ok=True)
    title = report_name
    ts = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    # pick images
    topic_sizes_img = str(viz / "topic_sizes.png") if (viz / "topic_sizes.png").exists() else ""
    # wordclouds: sorted by topic index
    wordcloud_imgs = ""
    for p in sorted(viz.glob("wordcloud_topic_*.png")):
        wordcloud_imgs += f'<div class="card"><h3>{p.stem}</h3><img src="../{p.as_posix()}" alt="{p.name}"></div>'

    # sentiment images
    sentiment_imgs = ""
    for p in sorted(viz.glob("sentiment_topic_*.png")):
        sentiment_imgs += f'<div class="card"><h3>{p.stem}</h3><img src="../{p.as_posix()}" alt="{p.name}"></div>'

    # summaries
    summary_cards = ""
    if summaries_path:
        sp = Path(summaries_path)
        if sp.exists():
            try:
                data = json.loads(sp.read_text(encoding="utf8"))
            except Exception:
                data = {}
            # data expected as {topic_idx: summary}
            for k in sorted(data.keys(), key=lambda x:int(x)):
                s = data[k]
                summary_cards += f'<div class="card"><h3>Topic {k}</h3><pre>{s}</pre></div>'
        else:
            summary_cards = '<div class="card">No summaries file found</div>'
    else:
        summary_cards = '<div class="card">No summaries provided</div>'

    html = HTML_TEMPLATE.format(
        title=title,
        ts=ts,
        viz_dir=viz_dir,
        top_words_path=top_words_path or "",
        summaries_path=summaries_path or "",
        topic_sizes_img=("../" + str(topic_sizes_img)) if topic_sizes_img else "",
        wordcloud_imgs=wordcloud_imgs,
        sentiment_imgs=sentiment_imgs,
        summary_cards=summary_cards
    )

    out_path = out_root / f"report_{report_name}.html"
    out_path.write_text(html, encoding="utf8")
    # Return relative path (so UI can serve it)
    return str(out_path)
