name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  python-lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install minimal deps
        run: |
          python -m pip install --upgrade pip
          pip install -r ml/requirements.txt
      - name: Smoke import app
        run: |
          python - <<'PY'
          import importlib.util, sys
          spec = importlib.util.spec_from_file_location('ml.app', 'ml/app.py')
          mod = importlib.util.module_from_spec(spec)
          spec.loader.exec_module(mod)
          print('Imported ml.app OK')
          PY
      - name: Validate notebook structure
        run: |
          python - <<'PY'
          import json
          with open('ml/nlp_tasks.ipynb', 'r', encoding='utf-8') as f:
              nb = json.load(f)
          assert 'cells' in nb and len(nb['cells']) > 0, 'Notebook has no cells'
          print('Notebook structure looks OK')
          PY
